# Generated by Django 5.1.1 on 2024-10-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('EVERYONE', 'Everyone'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS', 'Friends')], default='EVERYONE', max_length=10),
        ),
    ]
